language: perl
perl:
  - "5.20"

# Use this to prepare the system to install prerequisites or dependencies
before_install: true

# Use this to install any prerequisites or dependencies necessary to run your build
install:
  - cpanm Term::ProgressBar
#  - cpanm --installdeps Paranoid
  
  
#  - cpanm Parse::PlainConfig
  
# Use this to prepare your build for testing
# e.g. copy database configurations, environment variables, etc.
before_script: true

# Default is specific to project language
# All commands must exit with code 0 on success. 
# Anything else is considered failure.
script:
  #- echo -e `ps -ef | grep postgres | grep -v 'postgres:' | grep -v 'grep'`
  #- echo $PWD
  - cpanm CORLISS/Paranoid/Paranoid-0.34.tar.gz
  #- ./test.pl

after_success: true

after_failure:
  - ls /home/travis/.cpanm/work/*/build.log
